---
  - name : Install Docker and run container
    hosts : all
    become: true
    tasks : 
    - name: update apt
      command : sudo apt-get update
    
    - name: Install Python
      command : sudo apt-get install -y python3-pip

    - name : Install Docker
      command : sudo apt-get install -y docker.io
      become : yes
      become_user : root

    - name : Start Docker Service
      command : sudo systemctl start docker
      become : yes
      become_user : root
    - name : Runthe image as a container
      command : docker run -itd -p 8080:8081 snehalatha15/project:latest
